/**
 * Describes a process state for a proces that runs on a client.
 */
export enum ProcessState {
	STARTED, // APPLIATION HAS BEEN TRIGGERED TO START
	STOPPED, // APPLICATION WAS STOPPED BY THE SERVER MANUALLY
	RUNNING, // THE APPLICATION STARTED, AND IS NOT RUNNING
	TERMINATED, // THE APPLICATION GOT STOPPED, TERMINATED ABNORMALY
	UNKNOWN, // PROCESS HAS UNKNOWN STATE
}
